name: Android CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create .gradle
      run: mkdir -p ~/.gradle

    - name: Create gradle.properties
      run: |
        echo "RELEASE_STORE_FILE=$GITHUB_WORKSPACE/key.store
        RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" > ~/.gradle/gradle.properties

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: webview
        path: app/build/outputs/apk/release/*.apk
